# 화면
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
FPS = 60

# 색상
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 50, 50)
GREEN = (50, 255, 50)
BLUE = (50, 50, 255)
YELLOW = (255, 255, 0)
PURPLE = (200, 50, 255)
CYAN = (50, 255, 255)

# 게임 밸런스
INITIAL_LIVES = 3
INITIAL_LEVEL = 1
MAX_LEVEL = 4                    
INITIAL_NEXT_LEVEL_TARGET = 10
LEVEL_UP_DISPLAY_DURATION = 2000  # ms

# 입력값 설정
DB_THRESHOLD = 60.0             
SHOUT_COOLDOWN = 3000            # 소리치기 후 쿨타임 3초 (ms)
MIC_DB_MULTIPLIER = 7.0
MIC_DB_OFFSET = 0.0

# 단어 밀어내기 강도
SHOUT_PUSH_MULTIPLIER = 15.0

# 위치
BOSS_X = SCREEN_WIDTH - 80
BOSS_Y = SCREEN_HEIGHT // 2
PLAYER_X = 50

# 단어 스폰
SPAWN_DELAY_BASE = 2000
SPAWN_DELAY_MIN = 600
SPAWN_DELAY_LEVEL_REDUCTION = 200

# 레인 시스템
Y_LANES = [100, 160, 220, 280, 340, 400, 460, 520]
MAX_RECENT_LANES = 3

# 레벨별 단어 풀
LEVEL_WORD_POOLS = {
    1: [
        "CODE", "BUG", "GAME", "SAVE", "LOAD", "FILE", "PLAY", "STOP",
        "START", "RUN", "CAT", "DOG", "BIRD", "SKY", "TREE", "BOOK",
        "NOTE", "PEN", "MOUSE", "KEY", "HOME", "FOOD", "CAKE", "MILK",
        "FISH", "CHAT", "SONG", "RAIN", "SNOW", "SUN"
    ],
    2: [
        "DATA", "SERVER", "LOGIN", "LOGOUT", "BUTTON", "SCREEN", "WINDOW",
        "FOLDER", "UPLOAD", "DOWNLOAD", "PLAYER", "LEVEL", "QUEST", "ITEM",
        "SCORE", "ROBOT", "CLOUD", "SEARCH", "STREAM", "UPDATE", "LAPTOP",
        "CAMERA", "MOVIE", "SCHOOL", "FRIEND", "COFFEE", "ORANGE", "GARDEN",
        "BRIDGE", "MARKET"
    ],
    3: [
        "NETWORK", "BROWSER", "MEMORY", "OBJECT", "CLASS", "SYSTEM", "CODING",
        "RENDER", "ENGINE", "PROFILE", "COOKIE", "ONLINE", "PLAYER", "DESIGN",
        "PIXEL", "I LIKE GAMES.", "THE CODE WORKS.", "SAVE THE FILE.", "OPEN THE WINDOW.",
        "THE CAT SLEEPS.", "THE DOG RUNS.", "START THE GAME.", "CHECK THE SCORE.",
        "CLICK THE BUTTON.", "LOAD THE DATA.", "THE SKY IS BLUE.", "MUSIC IS PLAYING.",
        "THE SERVER IS READY.", "UPDATE COMPLETE.", "WELCOME BACK."
    ],
    4: [
        "THE GAME IS RUNNING.", "SAVE YOUR PROGRESS.", "THE SERVER IS ONLINE.",
        "THE CODE HAS A BUG.", "PLEASE TRY AGAIN.", "THE FILE WAS SAVED.",
        "LOADING DATA NOW.", "CLICK TO CONTINUE.", "THE UPDATE IS READY.",
        "YOUR SCORE INCREASED.", "THE PLAYER HAS JOINED.", "THE QUEST IS COMPLETE.",
        "THE NETWORK IS SLOW.", "THE SYSTEM IS STABLE.", "OPEN THE SETTINGS MENU.",
        "THE BROWSER IS OPEN.", "THE CAT IS SLEEPING.", "THE DOG WANTS FOOD.",
        "IT IS RAINING TODAY.", "THE MOVIE WAS FUN.", "THE COFFEE IS HOT.",
        "I FINISHED MY WORK.", "THE BRIDGE IS LONG.", "THE GARDEN LOOKS NICE.",
        "MUSIC MAKES ME HAPPY.", "THE SCREEN IS BRIGHT.", "WE WON THE GAME.",
        "THE ENGINE IS READY.", "CODING TAKES PRACTICE.", "THANKS FOR PLAYING."
    ]
}

# 전체 단어 풀 (레벨별 단어를 합친 참조용)
WORD_POOL = sorted({
    word
    for pool in LEVEL_WORD_POOLS.values()
    for word in pool
})

# 무거운 단어 확률
HEAVY_CHANCE_BASE = 0.1
HEAVY_CHANCE_PER_LEVEL = 0.05
HEAVY_CHANCE_MAX = 0.6

# 단어 속도 설정
WORD_SPEED_MIN = 0.8
WORD_SPEED_MAX = 1.8
WORD_SPEED_LEVEL_BONUS = 0.25   
WORD_SPEED_LIMIT = 3.5          

# 단어 진폭/주파수 범위
WORD_AMP_MIN = 15
WORD_AMP_MAX = 40
WORD_FREQ_MIN = 200.0
WORD_FREQ_MAX = 600.0

# 소리치기 밀어내기
SHOUT_PUSH_BASE = 6
SHOUT_PUSH_LEVEL_BONUS = 1